name: Dev Deployment

on:
  push:
    branches: ["main"]

permissions:
  id-token: write # Required for OIDC token exchange
  contents: read

concurrency:
  group: terraform-deployment
  cancel-in-progress: false

jobs:
  build_and_deploy_dev:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Login to Azure (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Run Terraform
        env:
          # Set environment variables from GitHub secrets
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          TF_VAR_azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          TF_VAR_azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          TF_VAR_azure_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          TF_VAR_resource_group_name: ${{ secrets.TF_BACKEND_RESOURCE_GROUP }}
          TF_VAR_storage_account_name: ${{ secrets.TF_BACKEND_STORAGE_ACCOUNT }}
          TF_VAR_container_name: ${{ secrets.TF_BACKEND_CONTAINER }}
          TF_VAR_backend_state_name: ${{ secrets.TF_BACKEND_STATE }}
        run: |
          echo "Initializing Terraform ..."
          terraform init \
            -backend-config="resource_group_name=$TF_VAR_resource_group_name" \
            -backend-config="storage_account_name=$TF_VAR_storage_account_name" \
            -backend-config="container_name=$TF_VAR_container_name" \
            -backend-config="key=$TF_VAR_backend_state_name" \
            -backend-config="subscription_id=$ARM_SUBSCRIPTION_ID"

          echo "Planning Terraform changes..."
          terraform plan -out=tfplan

          echo "Applying Terraform changes..."
          terraform apply -auto-approve tfplan
