name: Production DNS Deployment

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "**/*.tf"

permissions:
  id-token: write # Required for OIDC token exchange
  contents: read

concurrency:
  group: terraform-deployment
  cancel-in-progress: false

jobs:
  build_and_deploy:
    runs-on:
      - dns
    environment: production

    steps:
      - name: Check out source code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Login to Azure (OIDC)
        uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2
        with:
          client-id: ${{ env.SUB_ID }}
          tenant-id: ${{ env.TENANT }}
          subscription-id: ${{ env.SUB_ID }}

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: "22"

      - name: Install Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3

      - name: Run Terraform
        env:
          # Set environment variables from GitHub secrets
          TF_VAR_resource_group_name: ${{ secrets.TF_DNS_RESOURCE_GROUP }}
          TF_VAR_storage_account_name: ${{ secrets.TF_BACKEND_STORAGE_ACCOUNT }}
          TF_VAR_container_name: ${{ secrets.TF_BACKEND_CONTAINER }}
          TF_VAR_backend_state_name: ${{ secrets.TF_BACKEND_STATE }}
        run: |
          echo "Initializing Terraform ..."
          terraform init \
            -backend-config="resource_group_name=$TF_VAR_resource_group_name" \
            -backend-config="storage_account_name=$TF_VAR_storage_account_name" \
            -backend-config="container_name=$TF_VAR_container_name" \
            -backend-config="key=$TF_VAR_backend_state_name" \
            -backend-config="subscription_id=$ARM_SUBSCRIPTION_ID"

          echo "Planning Terraform changes..."
          terraform plan -out=tfplan

          echo "Applying Terraform changes..."
          #terraform apply -auto-approve tfplan
