name: Terraform Rules

on:
  push: {}
  pull_request:
    paths:
      - "**/*.tf"

jobs:
  policy-check:
    name: Terrascan Policy Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Run Terrascan
        uses: tenable/terrascan-action@v1
        with:
          iac_type: "terraform"
          policy_path: "policy"
